{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 6, "revision" : 4 },
		"classnamespace" : "box",
		"rect" : [100, 100, 800, 700],
		"bglocked" : 1,
		"openrect" : [0, 0, 0, 0],
		"openinpresentation" : 0,
		"default_fontsize" : 12,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 2,
		"gridsize" : [15, 15],
		"gridsnaponopen" : 0,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 2,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0,
		"description" : "Send audio via WebRTC",
		"digest" : "Captures audio from Max signal chain, Opus-encodes, and sends via WebRTC",
		"tags" : "webrtc, audio, network",
		"style" : "",
		"subpatcher_template" : "",
		"assistshowspatchername" : 0,
		"boxes" : [
			{ "box" : { "id" : "obj-1", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 30, 300, 20], "text" : "bbb.webrtc.send — Send audio via WebRTC" } },
			{ "box" : { "id" : "obj-2", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 55, 400, 20], "text" : "MSP signal in → Opus encode → WebRTC peer connection" } },
			{ "box" : { "id" : "obj-3", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [30, 110, 120, 20], "text" : "signal in" } },
			{ "box" : { "id" : "obj-4", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [50, 130, 50, 22], "text" : "adc~" } },
			{ "box" : { "id" : "obj-5", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 180, 400, 22], "text" : "bbb.webrtc.send @stun_server stun:stun.l.google.com:19302 @bitrate 64000" } },
			{ "box" : { "id" : "obj-6", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [470, 180, 180, 20], "text" : "→ SDP / ICE / status messages" } },
			{ "box" : { "id" : "obj-7", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "", "", "", "" ], "patching_rect" : [470, 220, 250, 22], "text" : "route offer answer candidate state" } },
			{ "box" : { "id" : "obj-8", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [470, 260, 80, 22], "text" : "print offer" } },
			{ "box" : { "id" : "obj-9", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [560, 260, 90, 22], "text" : "print answer" } },
			{ "box" : { "id" : "obj-10", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [660, 260, 110, 22], "text" : "print candidate" } },
			{ "box" : { "id" : "obj-11", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [740, 260, 80, 22], "text" : "print state" } },
			{ "box" : { "id" : "obj-12", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 320, 300, 20], "text" : "Messages:" } },
			{ "box" : { "id" : "obj-13", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 345, 60, 22], "text" : "offer" } },
			{ "box" : { "id" : "obj-14", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [130, 345, 80, 22], "text" : "close" } },
			{ "box" : { "id" : "obj-15", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [230, 345, 80, 22], "text" : "dump" } },
			{ "box" : { "id" : "obj-16", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 380, 200, 22], "text" : "answer <paste_remote_sdp_here>" } },
			{ "box" : { "id" : "obj-17", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 410, 250, 22], "text" : "candidate <paste_candidate_here> mid" } },
			{ "box" : { "id" : "obj-18", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 450, 300, 20], "text" : "Attributes: @stun_server @turn_server @turn_username @turn_password @bitrate" } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-4", 0 ], "destination" : [ "obj-5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-8", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 1 ], "destination" : [ "obj-9", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 2 ], "destination" : [ "obj-10", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 3 ], "destination" : [ "obj-11", 0 ] } },
			{ "patchline" : { "source" : [ "obj-13", 0 ], "destination" : [ "obj-5", 1 ] } },
			{ "patchline" : { "source" : [ "obj-14", 0 ], "destination" : [ "obj-5", 1 ] } },
			{ "patchline" : { "source" : [ "obj-15", 0 ], "destination" : [ "obj-5", 1 ] } },
			{ "patchline" : { "source" : [ "obj-16", 0 ], "destination" : [ "obj-5", 1 ] } },
			{ "patchline" : { "source" : [ "obj-17", 0 ], "destination" : [ "obj-5", 1 ] } }
		]
	}
}
