{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 6, "revision" : 4 },
		"classnamespace" : "box",
		"rect" : [50, 50, 1200, 850],
		"bglocked" : 1,
		"openrect" : [0, 0, 0, 0],
		"openinpresentation" : 0,
		"default_fontsize" : 12,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 2,
		"gridsize" : [15, 15],
		"gridsnaponopen" : 0,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 2,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0,
		"description" : "WebRTC video peer-to-peer loopback test",
		"digest" : "Test send.video → recv.video via WebRTC on localhost",
		"tags" : "webrtc, video, test",
		"style" : "",
		"subpatcher_template" : "",
		"assistshowspatchername" : 0,
		"boxes" : [
			{ "box" : { "id" : "obj-title", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 20, 500, 24], "fontsize" : 16, "text" : "bbb.webrtc — Video Loopback Test" } },
			{ "box" : { "id" : "obj-subtitle", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 48, 600, 20], "text" : "1. Toggle [qmetro] to start generating frames → Click [offer] on sender" } },
			{ "box" : { "id" : "obj-subtitle2", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 66, 600, 20], "text" : "2. Copy offer SDP from Max console → paste into [offer <sdp>] on receiver" } },
			{ "box" : { "id" : "obj-subtitle3", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 84, 600, 20], "text" : "3. Copy answer SDP from receiver console → paste into [answer <sdp>] on sender. Exchange ICE candidates." } },

			{ "box" : { "id" : "obj-send-label", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 120, 200, 20], "fontsize" : 14, "text" : "=== SENDER (Peer A) ===" } },

			{ "box" : { "id" : "obj-qmetro-toggle", "maxclass" : "toggle", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "int" ], "patching_rect" : [50, 150, 20, 20] } },
			{ "box" : { "id" : "obj-qmetro", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [50, 150, 70, 22], "text" : "qmetro 33" } },
			{ "box" : { "id" : "obj-noise", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_matrix", "" ], "patching_rect" : [50, 180, 110, 22], "text" : "jit.noise 640 480 4" } },
			{ "box" : { "id" : "obj-send", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 220, 450, 22], "text" : "bbb.webrtc.send.video @stun_server stun:stun.l.google.com:19302 @width 640 @height 480 @bitrate 2000000 @fps 30" } },
			{ "box" : { "id" : "obj-send-route", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "", "", "", "" ], "patching_rect" : [50, 260, 250, 22], "text" : "route offer answer candidate state" } },
			{ "box" : { "id" : "obj-send-offer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [50, 300, 90, 22], "text" : "print A-offer" } },
			{ "box" : { "id" : "obj-send-answer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [150, 300, 90, 22], "text" : "print A-answer" } },
			{ "box" : { "id" : "obj-send-cand-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [250, 300, 100, 22], "text" : "print A-candidate" } },
			{ "box" : { "id" : "obj-send-state-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [360, 300, 80, 22], "text" : "print A-state" } },

			{ "box" : { "id" : "obj-offer-btn", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 340, 60, 22], "text" : "offer" } },
			{ "box" : { "id" : "obj-send-answer-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [130, 340, 300, 22], "text" : "answer <paste_answer_sdp_here>" } },
			{ "box" : { "id" : "obj-send-cand-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [450, 340, 300, 22], "text" : "candidate <paste_candidate_here> 0" } },
			{ "box" : { "id" : "obj-send-close", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [770, 340, 60, 22], "text" : "close" } },

			{ "box" : { "id" : "obj-recv-label", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 400, 200, 20], "fontsize" : 14, "text" : "=== RECEIVER (Peer B) ===" } },
			{ "box" : { "id" : "obj-recv", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_matrix", "" ], "patching_rect" : [50, 430, 400, 22], "text" : "bbb.webrtc.recv.video @stun_server stun:stun.l.google.com:19302" } },
			{ "box" : { "id" : "obj-window", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [50, 470, 70, 22], "text" : "jit.window" } },
			{ "box" : { "id" : "obj-recv-route", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "", "", "", "" ], "patching_rect" : [500, 430, 250, 22], "text" : "route offer answer candidate state" } },
			{ "box" : { "id" : "obj-recv-offer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [500, 470, 90, 22], "text" : "print B-offer" } },
			{ "box" : { "id" : "obj-recv-answer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [600, 470, 90, 22], "text" : "print B-answer" } },
			{ "box" : { "id" : "obj-recv-cand-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [700, 470, 100, 22], "text" : "print B-candidate" } },
			{ "box" : { "id" : "obj-recv-state-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [810, 470, 80, 22], "text" : "print B-state" } },

			{ "box" : { "id" : "obj-recv-offer-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 510, 300, 22], "text" : "offer <paste_offer_sdp_here>" } },
			{ "box" : { "id" : "obj-recv-cand-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [370, 510, 300, 22], "text" : "candidate <paste_candidate_here> 0" } },
			{ "box" : { "id" : "obj-recv-close", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [690, 510, 60, 22], "text" : "close" } },

			{ "box" : { "id" : "obj-note", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 560, 600, 20], "text" : "NOTE: Same machine loopback — toggle qmetro ON, click offer, exchange SDPs and candidates via console." } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-qmetro-toggle", 0 ], "destination" : [ "obj-qmetro", 0 ] } },
			{ "patchline" : { "source" : [ "obj-qmetro", 0 ], "destination" : [ "obj-noise", 0 ] } },
			{ "patchline" : { "source" : [ "obj-noise", 0 ], "destination" : [ "obj-send", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send", 0 ], "destination" : [ "obj-send-route", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 0 ], "destination" : [ "obj-send-offer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 1 ], "destination" : [ "obj-send-answer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 2 ], "destination" : [ "obj-send-cand-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 3 ], "destination" : [ "obj-send-state-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-offer-btn", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-answer-msg", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-cand-msg", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-close", 0 ], "destination" : [ "obj-send", 1 ] } },

			{ "patchline" : { "source" : [ "obj-recv", 0 ], "destination" : [ "obj-window", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv", 1 ], "destination" : [ "obj-recv-route", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 0 ], "destination" : [ "obj-recv-offer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 1 ], "destination" : [ "obj-recv-answer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 2 ], "destination" : [ "obj-recv-cand-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 3 ], "destination" : [ "obj-recv-state-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-offer-msg", 0 ], "destination" : [ "obj-recv", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-cand-msg", 0 ], "destination" : [ "obj-recv", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-close", 0 ], "destination" : [ "obj-recv", 0 ] } }
		]
	}
}
