{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 6, "revision" : 4 },
		"classnamespace" : "box",
		"rect" : [50, 50, 1200, 800],
		"bglocked" : 1,
		"openrect" : [0, 0, 0, 0],
		"openinpresentation" : 0,
		"default_fontsize" : 12,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 2,
		"gridsize" : [15, 15],
		"gridsnaponopen" : 0,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 2,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0,
		"description" : "WebRTC peer-to-peer loopback test",
		"digest" : "Test send → recv via WebRTC on localhost",
		"tags" : "webrtc, test",
		"style" : "",
		"subpatcher_template" : "",
		"assistshowspatchername" : 0,
		"boxes" : [
			{ "box" : { "id" : "obj-title", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 20, 400, 24], "fontsize" : 16, "text" : "bbb.webrtc — Loopback Test" } },
			{ "box" : { "id" : "obj-subtitle", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 48, 500, 20], "text" : "1. Click [offer] on sender → copy SDP from Max console → paste into [offer <sdp>] on receiver" } },
			{ "box" : { "id" : "obj-subtitle2", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 66, 500, 20], "text" : "2. Copy answer SDP from receiver console → paste into [answer <sdp>] on sender" } },
			{ "box" : { "id" : "obj-subtitle3", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 84, 500, 20], "text" : "3. Exchange ICE candidates between both sides. State should become [connected]." } },

			{ "box" : { "id" : "obj-send-label", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 130, 200, 20], "fontsize" : 14, "text" : "=== SENDER (Peer A) ===" } },
			{ "box" : { "id" : "obj-adc", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [50, 160, 50, 22], "text" : "adc~ 1" } },
			{ "box" : { "id" : "obj-send", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 200, 400, 22], "text" : "bbb.webrtc.send @stun_server stun:stun.l.google.com:19302 @bitrate 64000" } },
			{ "box" : { "id" : "obj-send-route", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "", "", "", "" ], "patching_rect" : [50, 240, 250, 22], "text" : "route offer answer candidate state" } },
			{ "box" : { "id" : "obj-send-offer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [50, 280, 90, 22], "text" : "print A-offer" } },
			{ "box" : { "id" : "obj-send-answer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [150, 280, 90, 22], "text" : "print A-answer" } },
			{ "box" : { "id" : "obj-send-cand-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [250, 280, 100, 22], "text" : "print A-candidate" } },
			{ "box" : { "id" : "obj-send-state-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [360, 280, 80, 22], "text" : "print A-state" } },

			{ "box" : { "id" : "obj-offer-btn", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 320, 60, 22], "text" : "offer" } },
			{ "box" : { "id" : "obj-send-answer-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [130, 320, 300, 22], "text" : "answer <paste_answer_sdp_here>" } },
			{ "box" : { "id" : "obj-send-cand-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [450, 320, 300, 22], "text" : "candidate <paste_candidate_here> 0" } },
			{ "box" : { "id" : "obj-send-close", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [770, 320, 60, 22], "text" : "close" } },

			{ "box" : { "id" : "obj-recv-label", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 380, 200, 20], "fontsize" : 14, "text" : "=== RECEIVER (Peer B) ===" } },
			{ "box" : { "id" : "obj-recv", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "signal", "" ], "patching_rect" : [50, 410, 400, 22], "text" : "bbb.webrtc.recv @stun_server stun:stun.l.google.com:19302" } },
			{ "box" : { "id" : "obj-dac", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [50, 450, 50, 22], "text" : "ezdac~" } },
			{ "box" : { "id" : "obj-recv-route", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "", "", "", "" ], "patching_rect" : [500, 410, 250, 22], "text" : "route offer answer candidate state" } },
			{ "box" : { "id" : "obj-recv-offer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [500, 450, 90, 22], "text" : "print B-offer" } },
			{ "box" : { "id" : "obj-recv-answer-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [600, 450, 90, 22], "text" : "print B-answer" } },
			{ "box" : { "id" : "obj-recv-cand-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [700, 450, 100, 22], "text" : "print B-candidate" } },
			{ "box" : { "id" : "obj-recv-state-print", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [810, 450, 80, 22], "text" : "print B-state" } },

			{ "box" : { "id" : "obj-recv-offer-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [50, 490, 300, 22], "text" : "offer <paste_offer_sdp_here>" } },
			{ "box" : { "id" : "obj-recv-cand-msg", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [370, 490, 300, 22], "text" : "candidate <paste_candidate_here> 0" } },
			{ "box" : { "id" : "obj-recv-close", "maxclass" : "message", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [690, 490, 60, 22], "text" : "close" } },

			{ "box" : { "id" : "obj-instructions", "maxclass" : "comment", "numinlets" : 0, "numoutlets" : 0, "patching_rect" : [50, 540, 500, 40], "text" : "NOTE: Both peers must be on the same machine or network. ICE candidates may need to be exchanged manually. Check Max console for SDP output." } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-adc", 0 ], "destination" : [ "obj-send", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send", 0 ], "destination" : [ "obj-send-route", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 0 ], "destination" : [ "obj-send-offer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 1 ], "destination" : [ "obj-send-answer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 2 ], "destination" : [ "obj-send-cand-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-send-route", 3 ], "destination" : [ "obj-send-state-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-offer-btn", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-answer-msg", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-cand-msg", 0 ], "destination" : [ "obj-send", 1 ] } },
			{ "patchline" : { "source" : [ "obj-send-close", 0 ], "destination" : [ "obj-send", 1 ] } },

			{ "patchline" : { "source" : [ "obj-recv", 0 ], "destination" : [ "obj-dac", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv", 1 ], "destination" : [ "obj-recv-route", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 0 ], "destination" : [ "obj-recv-offer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 1 ], "destination" : [ "obj-recv-answer-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 2 ], "destination" : [ "obj-recv-cand-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-route", 3 ], "destination" : [ "obj-recv-state-print", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-offer-msg", 0 ], "destination" : [ "obj-recv", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-cand-msg", 0 ], "destination" : [ "obj-recv", 0 ] } },
			{ "patchline" : { "source" : [ "obj-recv-close", 0 ], "destination" : [ "obj-recv", 0 ] } }
		]
	}
}
